sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t skelcd-control-caasp-image .
    # list the installed packages (just for easier debugging)
  - docker run --rm -it skelcd-control-caasp-image rpm -qa | sort

script:
  # the builds can run sequentially, the build in Docker is fast and Docker isolates
  # the containers (the second run has the very same initial image as the first run)
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e BUILD_FLAVOR=caasp skelcd-control-caasp-image ./.travis.sh
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e BUILD_FLAVOR=kubic skelcd-control-caasp-image ./.travis.sh
